config/routes.rb
Zetta::Application.routes.draw do

  resources :metas
  resources :meta_detalhes
  
  #safra
  resources :safras
  resources :safra_brotados
  resources :servicos
  resources :safra_ardidos
  resources :safra_verdosos
  resources :safra_quebrados
  resources :safra_averiados
  resources :safra_umidades
  resources :safra_impurezas
  
  resources :safra_produtos do
    member do
      get 'descontos'
    end
  end 

  match 'zetta' => 'logins#new'
  match 'menu'  => 'menus#index'

  #buscas
  scope 'buscas' do
    match 'get_unidade'    => "buscas#get_unidade", :via => :post
    match 'get_usuario'    => "buscas#get_usuario", :via => :post
    match 'cotz_us_compra' => "buscas#cotz_us_compra", :via => :post
    match 'cotz_us_venda'  => "buscas#cotz_us_venda", :via => :post
    match 'cotz_rs_compra' => "buscas#cotz_rs_compra", :via => :post
    match 'cotz_rs_venda'  => "buscas#cotz_rs_venda", :via => :post
    match 'busca_produto'  => "buscas#busca_produto", :via => :get   
  end

  scope 'geradors' do
    match 'gerador_arquivo'  => "geradors#gerador_arquivo", :via => :get
    match 'result_gerador'   => "geradors#result_gerador", :via => :get
  end
  #login
  resources :logins do
    collection do
      get 'acesso'
      get 'liberacao'
      post 'logar'
      post 'get_unidade'
    end
  end

  #cadastros
  resources :localizacaos
  resources :produto_barras
  resources :localidades
  resources :metodos
  resources :equipos
  resources :servicos
  resources :variavels
  resources :elementos
  resources :unidade_metricas
  resources :empresas
  resources :contas
  resources :sub_grupos
  resources :depositos
  resources :bicos
  resources :grupos
  resources :usuarios
  resources :unidades
  resources :clases
  resources :rodados
  resources :documentos
  resources :metas
  resources :meta_detalhes
  resources :planos
  resources :plano_de_contas do
    collection do
      get 'print'
    end
  end 
  resources :moedas
  resources :cidades
  resources :estados
  resources :paises
  resources :setors
  resources :personas do
    collection do
      get 'persona_nota_credito'
      get 'persona_cobro'
      get 'persona_pago'
      get 'busca_persona_pago'                    
      get 'busca_persona_cobro'                  
      get 'persona_presupuesto'                  
      get 'persona_nota_credito_proveedor'       
      get 'busca_persona_presupuesto'            
      get 'busca'                                
      get 'persona_compra'                 
      get 'busca_persona_compra'                 
      get 'busca_cliente'                        
      get 'busca_persona_nota_credito'           
      get 'busca_persona_nota_credito_proveedor' 
      get 'busca_persona_venda_financa'          
      get 'busca_persona_venda'
      get 'persona_venda'
    end
    member do 
      get 'tarjeta'
    end
  end                   
  resources :produtos do
    collection do
      get 'dinamic_busca_consulta_stock'             
      get 'index_print'                              
      get 'consulta_stock'                           
      get 'busca_compra_produto'                     
      get 'dinamic_busca_compra_produto'             
      get 'busca_composicao_produto'                 
      get 'dinamic_busca_composicao_produto'         
      get 'busca_pedido_compra_produto'              
      get 'dinamic_busca_pedido_compra_produto'      
      get 'busca_presupuesto_produto'                
      get 'dinamic_busca_presupuesto_produto'        
      get 'busca_venda_produto'                      
      get 'dinamic_busca_venda_produto'              
      get 'busca_consumicao_interna_produto'         
      get 'dinamic_busca_consumicao_interna_produto' 
      get 'busca_manutencao_mq_produto'              
      get 'dinamic_busca_manutencao_mq_produto'      
      get 'busca_producao_produto'                   
      get 'dinamic_busca_producao_produto'           
      get 'busca_remicao_produto'                    
      get 'dinamic_busca_remicao_produto'            
      get 'busca_venda_produto_maiorista'            
      get 'dinamic_busca_venda_produto_maiorista'    
      get 'dinamic_busca'                            
      get 'busca_ordem_produto'                      
      get 'dinamic_busca_ordem_produto'              
      get 'imagem'                                  
    end
    member do
      get 'cod_barra'
      get 'roteiro'
      get 'composicao'

    end
  end  
  resources :financas do
    collection do
      get 'relatorio_financas'
      get 'extrato_bancario'
      get 'resultado_extrato_bancario'    

    end  
  end
  resources :forms

  #processos
  resources :controle_pulv_maqs
  resources :controle_pulvs  
  resources :controle_visita
  resources :setores
  #
  resources :controle_pulvs
  resources :controle_visita
  #COMPRAS
  resources :compras_gastos
  resources :compras_documentos
  resources :compras_produtos
  resources :compras_financas
  resources :compras do
    collection do
      get 'busca' 
      get 'busca_gasto'      
      get 'compras_gasto'     
      get 'compras_financa'   
      get 'compras_documento'             
      get 'novo_financa'      
      get 'novo_gasto'        
      get 'new_gasto'
      get 'index_gasto'
      get 'pedido_compras'
    end  
    member do 
      get "compras_financa"
      get "novo_financa" 
      get "edit_gasto"     
      get 'novo_produto'
      get 'compras_documento'
      get 'total_documento'
      get 'novo_documento'
      get 'prorateo'
    end
  end  
  resources :stocks do
    collection do
      get 'iventario'
      get 'stock_inicial'
      get 'relatorio_stock'                  
      get 'rentabilidade'                    
      get 'resultado_rentabilidade'       
      get 'dinamic_busca_stock_inicial'    
      get 'resultado_iventario'              
      get 'resultado_relatorio_consumo_bomba'
      get 'projecao_compras'
      get 'resultado_projecao_compras'      
    end
  end
  resources :pagares do
    member do
      get 'autorizacao_desc'
      get 'print'
    end
  end
   
  
resources :pagares_detalhe

  resources :consumicao_internas do 
    resources :consumicao_interna_produtos  
  end
  resources :ingressos do
    collection do
      get 'busca_ingreso'
    end
    member do
      get 'comprovante'
    end
  end

  resources :presupuestos
  resources :vendas do
    collection do
      get  'new_balcao'
      get  'venda_produto'
      get  'faturas_pendentes'                     
      get  'comprovante'                          
      get  'comprovante_fatura_pendentes'          
      get  'detalhes_produto'                      
      get  'busca_vendas'
      get  'vendas_financa_contado'               
      get  'vendas_financa' 
      get  'gerar_cotas_credito'
      get  'busca_vendas'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante'       
      get  'vendas_entrada_produto'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante' 
      put  'update_faturas_pendentes'  
    end
    member do
      get  'vendas_financa'
      get  'gerador_cotas'
      get  'comprovante'
      get  'fatura'
      get  'ticket'
    end 
  end
  resources :vendas_financas

  resources :vendas_produtos
  
  resources :producaos do
    collection do
      get 'busca'
      get 'producao_final'
    end
    resources :producao_produtos do 
      collection do 
        get 'detalhe_print'
      end 
    end 
  end  

  resources :manutencao_maquinas do
    resources :manutencao_maquina_produtos
  end
  resources :recepcao_nota_remicao_produtos
  resources :recepcao_nota_remicaos
  resources :nota_remicao_produtos
  resources :nota_remicaos
  resources :nota_creditos_detalhes
  resources :nota_creditos
  resources :nota_credito_proveedors do
    collection do
      get 'filtro_busca_faturas'
      get 'nc_proveedor_financa'
      get 'nota_credito_comprovante'
    end
  end
  resources :vendas_entrada_produtos
  
  resources :cobros_detalhes
  resources :cobros_financas
  resources :cobros do
    collection do      
      get 'busca'      
      get 'nova_cota'      
      get 'filtro_busca_cliente' 
      get 'busca'
      get 'nova_cota'
    end
    member do 
      get 'filtro_busca_cliente'
      get 'cobro_final'
    end
  end                        
  resources :pagos do
    collection do
      post 'filtro_dividas'
      get  'busca'      
    end
    member do 
      get 'pago_final'
    end
  end
  resources :pagos_detalhes
  resources :pagos_financas
  resources :egressos do
    collection do
      get 'busca_egreso'
      get 'comprovante'
    end
  end
  resources :transferencia_contas_detalhes
  resources :transferencia_contas do
    collection do
      get 'busca_diferido'
      get 'resultado_busca_diferido'
      get 'busca'
    end
  end
  resources :transferencia_entre_contas
  resources :fechamento_caixas
  resources :sueldos_detalhes

  resources :sueldos do
    collection do
      get 'form_sueldos_detalhes'
    end
    member do
      get 'form_sueldos_detalhes'
      get 'comprovante'
    end
  end 
  
  resources :adelantos do
    collection do
      get 'busca'
    end
    member do 
      get 'comprovante'
      get 'recibo'
    end 
  end  
  resources :pedido_compras do
    collection do 
      get 'busca_pedido_compra'
    end
  end
  resources :transferencia_depositos
  resources :entrada_saida_func_detalhes
  resources :entrada_saida_funcs do
    collection do
      get 'busca'
    end
  end

  resources :clientes do
    collection do
      get 'relatorio_contas_receber'
      get 'atualizacao_carpeta_cliente' 
      get 'busca_atualizacao_carpeta_cliente'
      get 'index_inicio'
    end
  end

  resources :proveedores do
    collection do
      get 'relatorio_contas_pagar'
      get 'index_inicio'
    end
  end

  resources :relatorios do
    collection do

app/models/meta.rb
class Meta < ActiveRecord::Base

  has_many :meta_detalhes, :dependent => :destroy

  validates :moeda, :periodo_final, :periodo_inicio, :status, :presence => true
  
end

app/controllers/metas_controller.rb
class MetasController < ApplicationController
  # GET /metas
  # GET /metas.json
  def index
    @metas = Meta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @metas }
    end
  end

  # GET /metas/1
  # GET /metas/1.json
  def show
    @meta = Meta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meta }
    end
  end

  # GET /metas/new
  # GET /metas/new.json
  def new
    @meta = Meta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meta }
    end
  end

  # GET /metas/1/edit
  def edit
    @meta = Meta.find(params[:id])
  end

  # POST /metas
  # POST /metas.json
  def create
    @meta = Meta.new(params[:meta])

    respond_to do |format|
      if @meta.save
        format.html { redirect_to @meta, notice: 'Meta was successfully created.' }
        format.json { render json: @meta, status: :created, location: @meta }
      else
        format.html { render action: "new" }
        format.json { render json: @meta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /metas/1
  # PUT /metas/1.json
  def update
    @meta = Meta.find(params[:id])

    respond_to do |format|
      if @meta.update_attributes(params[:meta])
        format.html { redirect_to @meta, notice: 'Meta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metas/1
  # DELETE /metas/1.json
  def destroy
    @meta = Meta.find(params[:id])
    @meta.destroy

    respond_to do |format|
      format.html { redirect_to metas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/helpers/metas_helper.rb
module MetasHelper
end

app/views/metas/_form.html.erb
<%= form_for(@meta) do |f| %>
  <% if @meta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meta.errors.count, "error") %> prohibited this meta from being saved:</h2>

      <ul>
      <% @meta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="tabs">
      <li><a href="#tab1">Metas - [Edicion]</a></li>
   </ul>

   <div class="tab_container">
      <div id="tab1" class="tab_content">

        <table>
          <tr>
            <td width="800" colspan="2">
              <fieldset>
                <legend>Periodo</legend>
                <table>
                  <tr>
                    <td align="right">Inicio :</td>
                    <td colspan="1"><%= f.date_select :periodo_inicio %></td>                        
                
                    <td align="right">Final :</td>
                    <td colspan="1"><%= f.date_select :periodo_final %></td>                        
                  </tr>
                </table>
              </fieldset>
            </td>
          </tr>

          <tr>
            <td  valign="top" >
              <fieldset>
                <legend>Moneda</legend>
                <table>
                  <tr>
                    <td><%= f.radio_button :moeda, 0, :checked => true %>DOLAR </td>
                  </tr>
                  <tr>
                    <td><%= f.radio_button :moeda, 1 %>GUARANI</td>
                  </tr>
                  <tr>
                    <td><%= f.radio_button :moeda, 2 %>REAL</td>
                  </tr>
                </table>                                                                                  
              </fieldset>
            </td>

            <td>
              <fieldset>
              <legend>Valores</legend>
              <table>
                <tr>
                  <%= field_us 'Min. U$:',f,:valor_min_us %>
                  <%= field_us 'Max. U$:',f,:valor_max_us %>
                </tr>

                <tr>
                  <%= field_gs 'Min. Gs:',f,:valor_min_gs %>
                  <%= field_gs 'Max. Gs:',f,:valor_max_gs %>
                </tr>

                <tr>
                  <%= field_us 'Min. R$:',f,:valor_min_rs %>
                  <%= field_us 'Max. R$:',f,:valor_max_rs %>

                </tr>
              </table>
              </fieldset>
            </td>
          </tr>            

          <tr>
            <td colspan="2">
              <fieldset>
                <legend>Status</legend>
                  <%= f.radio_button :status, 0, :checked => true %>ATIVO
                  <%= f.radio_button :status, 1 %>INATIVO
              </fieldset>
            </td>
          </tr>

          <tr>              
            <td colspan="2" valign="top"> Concepto :<%= f.text_area :descricao,
                                       :cols => 135, :rows => 6 %></td>
          
          </tr>


        </table>
      </div>
      <div class="buttons">
        <%= f.submit :value => "Seguir", :class => "button" %>
        <%= link_to 'Salir', metas_path, :class => "button back" %>
      </div>
      <% end %>
</div>

app/views/metas/edit.html.erb
<%= render 'form' %>

app/views/metas/index.html.erb
<body onload="ImputFocus('tipo')">
<h1 align="right" id="header">Metas</h1>
<div class="acessos">
   <%= link_to 'Nuevo', new_meta_path, :class => "button add" %>
</div>

<div class="group">
  <table>
    <tr>
      <td width="100" align="center">Periodo Inicial</td>
      <td width="100" align="center">Periodo Final</td>
      <td width="100" align="center">Status</td>
      <td width="100" align="center">Valor Min. U$</td>
      <td width="100" align="center">Valor Max. U$</td>
      <td width="100" align="center">Valor Min. G$</td>
      <td width="100" align="center">Valor Max. G$</td>
      <td width="100" align="center">Valor Min. R$</td>
      <td width="100" align="center">Valor Max. R$</td>
    </tr>
  </table>
  <div class="rolagem" dir="div">


    <table>
      <% @metas.each do |meta| %>
        <tr class = "<%= cycle("cor1", "cor2") %>">
          <td width="100"  align="center">    <%= h meta.periodo_inicio.strftime("%d/%m/%Y") %></td>
          <td width="100" align="center">    <%= h meta.periodo_final.strftime("%d/%m/%Y") %></td>
          <td width="100" align="left"  >    <%= h meta.status %></td>
          <td width="100" align="left"  >    <%= h meta.valor_min_us %></td>
          <td width="100"  align="center">    <%= h meta.valor_max_us %></td>
          <td width="100"  align="center">    <%= h meta.valor_min_gs %></td>
          <td width="100"  align="center">    <%= h meta.valor_max_gs %></td>
          <td width="100"  align="center">    <%= h meta.valor_min_rs %></td>
          <td width="100"  align="center">    <%= h meta.valor_max_rs %></td>

          <td><%= link_to 'Editar', edit_meta_path(meta) %></td>
          <td><%= link_to 'Borrar', meta, :confirm => 'Tiene Certeza?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/metas/new.html.erb
<%= render 'form' %>

app/views/metas/show.html.erb
  <ul class="tabs">
      <li><a href="#tab1">Metas - [Edicion]</a></li>
   </ul>

   <div class="tab_container">
   		<br>
      	<div class="group">
      		<b>Fecha Inicio:</b>
					<%= @meta.periodo_inicio.strftime("%d/%m/%Y") %>
  				<b>Fecha Final:</b>
  				<%= @meta.periodo_final.strftime("%d/%m/%Y") %>
  				<br>
  				<% if @meta.moeda == 0 %>
  					Meta Min. <%= number_to_currency( @meta.valor_min_us,      :format =>' %n ', :separeitor => "," )%>
  					Max. <%= number_to_currency( @meta.valor_max_us,      :format =>' %n ', :separeitor => "," )%>
  				<% elsif @meta.moeda == 1 %>
  					Meta Min. <%= number_to_currency( @meta.valor_min_gs,      :format =>' %n ', :precision => 0 )%>
  					Max. <%= number_to_currency( @meta.valor_max_gs,      :format =>' %n ', :precision => 0 )%>
  				<% else %>
  					Meta Min. <%= number_to_currency( @meta.valor_min_rs,      :format =>' %n ', :separeitor => "," )%>
  					Max. <%= number_to_currency( @meta.valor_max_rs,      :format =>' %n ', :separeitor => "," )%>
  				<% end %>
  				
      	</div>
      	<div class="group">
			  	<%= render :partial=>"/meta_detalhes/index_detalhes", :locals=>{:meta_detalhes => @meta.meta_detalhes}%>
			  </div>
				<%= render :partial=>"/meta_detalhes/new_detalhes", :locals=>{ :meta_detalhe => MetaDetalhe.new(:meta_id=>@meta.id) } %> 
        <div class="buttons">
        <%= link_to 'Volver', edit_meta_path(@meta), :class => "button back" %>
        <%= link_to 'Salir', metas_path, :class => "button next" %>

      </div>
  	</div>