config/routes.rb
Zetta::Application.routes.draw do

  resources :metas
  resources :meta_detalhes
  
  #safra
  resources :safras
  resources :safra_brotados
  resources :servicos
  resources :safra_ardidos
  resources :safra_verdosos
  resources :safra_quebrados
  resources :safra_averiados
  resources :safra_umidades
  resources :safra_impurezas
  
  resources :safra_produtos do
    member do
      get 'descontos'
    end
  end 

  match 'zetta' => 'logins#new'
  match 'menu'  => 'menus#index'

  #buscas
  scope 'buscas' do
    match 'get_unidade'    => "buscas#get_unidade", :via => :post
    match 'get_usuario'    => "buscas#get_usuario", :via => :post
    match 'cotz_us_compra' => "buscas#cotz_us_compra", :via => :post
    match 'cotz_us_venda'  => "buscas#cotz_us_venda", :via => :post
    match 'cotz_rs_compra' => "buscas#cotz_rs_compra", :via => :post
    match 'cotz_rs_venda'  => "buscas#cotz_rs_venda", :via => :post
    match 'busca_produto'  => "buscas#busca_produto", :via => :get   
  end

  scope 'geradors' do
    match 'gerador_arquivo'  => "geradors#gerador_arquivo", :via => :get
    match 'result_gerador'   => "geradors#result_gerador", :via => :get
  end
  #login
  resources :logins do
    collection do
      get 'acesso'
      get 'liberacao'
      post 'logar'
      post 'get_unidade'
    end
  end

  #cadastros
  resources :localizacaos
  resources :produto_barras
  resources :localidades
  resources :metodos
  resources :equipos
  resources :servicos
  resources :variavels
  resources :elementos
  resources :unidade_metricas
  resources :empresas
  resources :contas
  resources :sub_grupos
  resources :depositos
  resources :bicos
  resources :grupos
  resources :usuarios
  resources :unidades
  resources :clases
  resources :rodados
  resources :documentos
  resources :metas
  resources :meta_detalhes
  resources :planos
  resources :plano_de_contas do
    collection do
      get 'print'
    end
  end 
  resources :moedas
  resources :cidades
  resources :estados
  resources :paises
  resources :setors
  resources :personas do
    collection do
      get 'persona_nota_credito'
      get 'persona_cobro'
      get 'persona_pago'
      get 'busca_persona_pago'                    
      get 'busca_persona_cobro'                  
      get 'persona_presupuesto'                  
      get 'persona_nota_credito_proveedor'       
      get 'busca_persona_presupuesto'            
      get 'busca'                                
      get 'persona_compra'                 
      get 'busca_persona_compra'                 
      get 'busca_cliente'                        
      get 'busca_persona_nota_credito'           
      get 'busca_persona_nota_credito_proveedor' 
      get 'busca_persona_venda_financa'          
      get 'busca_persona_venda'
      get 'persona_venda'
    end
    member do 
      get 'tarjeta'
    end
  end                   
  resources :produtos do
    collection do
      get 'dinamic_busca_consulta_stock'             
      get 'index_print'                              
      get 'consulta_stock'                           
      get 'busca_compra_produto'                     
      get 'dinamic_busca_compra_produto'             
      get 'busca_composicao_produto'                 
      get 'dinamic_busca_composicao_produto'         
      get 'busca_pedido_compra_produto'              
      get 'dinamic_busca_pedido_compra_produto'      
      get 'busca_presupuesto_produto'                
      get 'dinamic_busca_presupuesto_produto'        
      get 'busca_venda_produto'                      
      get 'dinamic_busca_venda_produto'              
      get 'busca_consumicao_interna_produto'         
      get 'dinamic_busca_consumicao_interna_produto' 
      get 'busca_manutencao_mq_produto'              
      get 'dinamic_busca_manutencao_mq_produto'      
      get 'busca_producao_produto'                   
      get 'dinamic_busca_producao_produto'           
      get 'busca_remicao_produto'                    
      get 'dinamic_busca_remicao_produto'            
      get 'busca_venda_produto_maiorista'            
      get 'dinamic_busca_venda_produto_maiorista'    
      get 'dinamic_busca'                            
      get 'busca_ordem_produto'                      
      get 'dinamic_busca_ordem_produto'              
      get 'imagem'                                  
    end
    member do
      get 'cod_barra'
      get 'roteiro'
      get 'composicao'

    end
  end  
  resources :financas do
    collection do
      get 'relatorio_financas'
      get 'extrato_bancario'
      get 'resultado_extrato_bancario'    

    end  
  end
  resources :forms

  #processos
  resources :controle_pulv_maqs
  resources :controle_pulvs  
  resources :controle_visita
  resources :setores
  #
  resources :controle_pulvs
  resources :controle_visita
  #COMPRAS
  resources :compras_gastos
  resources :compras_documentos
  resources :compras_produtos
  resources :compras_financas
  resources :compras do
    collection do
      get 'busca' 
      get 'busca_gasto'      
      get 'compras_gasto'     
      get 'compras_financa'   
      get 'compras_documento'             
      get 'novo_financa'      
      get 'novo_gasto'        
      get 'new_gasto'
      get 'index_gasto'
      get 'pedido_compras'
    end  
    member do 
      get "compras_financa"
      get "novo_financa" 
      get "edit_gasto"     
      get 'novo_produto'
      get 'compras_documento'
      get 'total_documento'
      get 'novo_documento'
      get 'prorateo'
    end
  end  
  resources :stocks do
    collection do
      get 'iventario'
      get 'stock_inicial'
      get 'relatorio_stock'                  
      get 'rentabilidade'                    
      get 'resultado_rentabilidade'       
      get 'dinamic_busca_stock_inicial'    
      get 'resultado_iventario'              
      get 'resultado_relatorio_consumo_bomba'
      get 'projecao_compras'
      get 'resultado_projecao_compras'      
    end
  end
  resources :pagares do
    member do
      get 'autorizacao_desc'
      get 'print'
    end
  end
   
  
resources :pagares_detalhe

  resources :consumicao_internas do 
    resources :consumicao_interna_produtos  
  end
  resources :ingressos do
    collection do
      get 'busca_ingreso'
    end
    member do
      get 'comprovante'
    end
  end

  resources :presupuestos
  resources :vendas do
    collection do
      get  'new_balcao'
      get  'venda_produto'
      get  'faturas_pendentes'                     
      get  'comprovante'                          
      get  'comprovante_fatura_pendentes'          
      get  'detalhes_produto'                      
      get  'busca_vendas'
      get  'vendas_financa_contado'               
      get  'vendas_financa' 
      get  'gerar_cotas_credito'
      get  'busca_vendas'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante'       
      get  'vendas_entrada_produto'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante' 
      put  'update_faturas_pendentes'  
    end
    member do
      get  'vendas_financa'
      get  'gerador_cotas'
      get  'comprovante'
      get  'fatura'
      get  'ticket'
    end 
  end
  resources :vendas_financas

  resources :vendas_produtos
  
  resources :producaos do
    collection do
      get 'busca'
      get 'producao_final'
    end
    resources :producao_produtos do 
      collection do 
        get 'detalhe_print'
      end 
    end 
  end  

  resources :manutencao_maquinas do
    resources :manutencao_maquina_produtos
  end
  resources :recepcao_nota_remicao_produtos
  resources :recepcao_nota_remicaos
  resources :nota_remicao_produtos
  resources :nota_remicaos
  resources :nota_creditos_detalhes
  resources :nota_creditos
  resources :nota_credito_proveedors do
    collection do
      get 'filtro_busca_faturas'
      get 'nc_proveedor_financa'
      get 'nota_credito_comprovante'
    end
  end
  resources :vendas_entrada_produtos
  
  resources :cobros_detalhes
  resources :cobros_financas
  resources :cobros do
    collection do      
      get 'busca'      
      get 'nova_cota'      
      get 'filtro_busca_cliente' 
      get 'busca'
      get 'nova_cota'
    end
    member do 
      get 'filtro_busca_cliente'
      get 'cobro_final'
    end
  end                        
  resources :pagos do
    collection do
      post 'filtro_dividas'
      get  'busca'      
    end
    member do 
      get 'pago_final'
    end
  end
  resources :pagos_detalhes
  resources :pagos_financas
  resources :egressos do
    collection do
      get 'busca_egreso'
      get 'comprovante'
    end
  end
  resources :transferencia_contas_detalhes
  resources :transferencia_contas do
    collection do
      get 'busca_diferido'
      get 'resultado_busca_diferido'
      get 'busca'
    end
  end
  resources :transferencia_entre_contas
  resources :fechamento_caixas
  resources :sueldos_detalhes

  resources :sueldos do
    collection do
      get 'form_sueldos_detalhes'
    end
    member do
      get 'form_sueldos_detalhes'
      get 'comprovante'
    end
  end 
  
  resources :adelantos do
    collection do
      get 'busca'
    end
    member do 
      get 'comprovante'
      get 'recibo'
    end 
  end  
  resources :pedido_compras do
    collection do 
      get 'busca_pedido_compra'
    end
  end
  resources :transferencia_depositos
  resources :entrada_saida_func_detalhes
  resources :entrada_saida_funcs do
    collection do
      get 'busca'
    end
  end

  resources :clientes do
    collection do
      get 'relatorio_contas_receber'
      get 'atualizacao_carpeta_cliente' 
      get 'busca_atualizacao_carpeta_cliente'
      get 'index_inicio'
    end
  end

  resources :proveedores do
    collection do
      get 'relatorio_contas_pagar'
      get 'index_inicio'
    end
  end

  resources :relatorios do
    collection do

app/models/variavel.rb
class Variavel < ActiveRecord::Base

  validates :nome, :sigla, :valor, :presence => true

  belongs_to :unidade_metricas

  before_save :finds

  def finds
  	#busca unidade_metrica
	  uni_met = UnidadeMetrica.find_by_id(self.unidade_metrica_id);
	  self.unidade_metrica_nome = uni_met.nome.to_s unless self.unidade_metrica_id.blank?
  end 

end

app/controllers/variavels_controller.rb
class VariavelsController < ApplicationController
  # GET /variavels
  # GET /variavels.json
  def index
    @variavels = Variavel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @variavels }
    end
  end

  # GET /variavels/1
  # GET /variavels/1.json
  def show
    @variavel = Variavel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @variavel }
    end
  end

  # GET /variavels/new
  # GET /variavels/new.json
  def new
    @variavel = Variavel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @variavel }
    end
  end

  # GET /variavels/1/edit
  def edit
    @variavel = Variavel.find(params[:id])
  end

  # POST /variavels
  # POST /variavels.json
  def create
    @variavel = Variavel.new(params[:variavel])

    respond_to do |format|
      if @variavel.save
      format.html { redirect_to variavels_url }
      format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @variavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /variavels/1
  # PUT /variavels/1.json
  def update
    @variavel = Variavel.find(params[:id])

    respond_to do |format|
      if @variavel.update_attributes(params[:variavel])
      format.html { redirect_to variavels_url }
      format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @variavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variavels/1
  # DELETE /variavels/1.json
  def destroy
    @variavel = Variavel.find(params[:id])
    @variavel.destroy

    respond_to do |format|
      format.html { redirect_to variavels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/variavels_helper.rb
module VariavelsHelper
end

app/views/variavels/_form.html.erb
<%= form_for(@variavel) do |f| %>
  <% if @variavel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variavel.errors.count, "error") %> prohibited this variavel from being saved:</h2>

      <ul>
      <% @variavel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul class="tabs">
      <li><a href="#tab1">Variables - [Edicion]</a></li>
   </ul>

    <div class="tab_container">
      <div id="tab1" class="tab_content">
        <table>
          <tr>
            <td width="1000">
              <fieldset>
                <table>
                  <tr>
                    <td align="right">Nombre :</td>
                    <td><%= f.text_field :nome, :size => 80 %></td>                        

                    <td align="right">Sigla :</td>
                    <td><%= f.text_field :sigla, :size => 30 %></td>  
                  </tr>

                  <tr>
                    <td align="right">Valor :</td>
                    <td><%= f.text_field :valor, :size => 30 %></td>  
                  </tr>

                  <tr>
                    <td align="right">Unidad Métrica :</td>
                    <td colspan="4"><%= f.collection_select :unidade_metrica_id, UnidadeMetrica.all( :select => ' id,nome',
                                                            :order  => '2' ), 
                                                            :id,
                                                            :nome %></td>
                  </tr>

                  <%= f.hidden_field :unidade_metrica_nome %>

                </table>
              </fieldset>
            </td>
          </tr>
        </table>
      </div>
    </div>

    <div class="buttons">
      <%= f.submit :value => " Grabar ", :class => "button" %>
      <%= link_to 'Volver', variavels_path, :class => "button back" %>
    </div>
<% end %>

app/views/variavels/edit.html.erb
<h1>Editing variavel</h1>

<%= render 'form' %>

<%= link_to 'Show', @variavel %> |
<%= link_to 'Back', variavels_path %>

app/views/variavels/index.html.erb
<h1 align="right" id="header">Variables</h1>
<div class="acessos">
   <%= link_to 'Nuevo', new_variavel_path, :class => "button add" %>
</div>

<table class="head_grid">
          <tr>
            <td width="50" align="center">Sigla</td>
            <td width="400" align="center">Nombre</td>
            <td width="250" align="center">Unidad Métrica</td>
            <td width="50" align="center">Valor</td>
          </tr>
</table>

<div class="rolagem" dir="div">
<table>
<% @variavels.each do |variavel| %>
  <tr class = "<%= cycle("cor1", "cor2") %>">
    <td width="50" align="center"><%= variavel.sigla %></td>
    <td width="400" align="left"><%= variavel.nome %></td>
    <td width="250" align="left"><%= variavel.unidade_metrica_nome %></td>
    <td width="50" align="left"><%= variavel.valor %></td>

    <td><%= link_to 'Editar', edit_variavel_path(variavel) %></td>
    <td><%= link_to 'Borrar', variavel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>

app/views/variavels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @variavel.nome %>
</p>

<p>
  <b>Sigla:</b>
  <%= @variavel.sigla %>
</p>

<p>
  <b>Valor:</b>
  <%= @variavel.valor %>
</p>

<p>
  <b>Unidade metrica:</b>
  <%= @variavel.unidade_metrica_id %>
</p>

<p>
  <b>Unidade metrica nome:</b>
  <%= @variavel.unidade_metrica_nome %>
</p>


<%= link_to 'Edit', edit_variavel_path(@variavel) %> |
<%= link_to 'Back', variavels_path %>