config/routes.rb
Zetta::Application.routes.draw do

  resources :metas
  resources :meta_detalhes
  
  #safra
  resources :safras
  resources :safra_brotados
  resources :servicos
  resources :safra_ardidos
  resources :safra_verdosos
  resources :safra_quebrados
  resources :safra_averiados
  resources :safra_umidades
  resources :safra_impurezas
  
  resources :safra_produtos do
    member do
      get 'descontos'
    end
  end 

  match 'zetta' => 'logins#new'
  match 'menu'  => 'menus#index'

  #buscas
  scope 'buscas' do
    match 'get_unidade'    => "buscas#get_unidade", :via => :post
    match 'get_usuario'    => "buscas#get_usuario", :via => :post
    match 'cotz_us_compra' => "buscas#cotz_us_compra", :via => :post
    match 'cotz_us_venda'  => "buscas#cotz_us_venda", :via => :post
    match 'cotz_rs_compra' => "buscas#cotz_rs_compra", :via => :post
    match 'cotz_rs_venda'  => "buscas#cotz_rs_venda", :via => :post
    match 'busca_produto'  => "buscas#busca_produto", :via => :get   
  end

  scope 'geradors' do
    match 'gerador_arquivo'  => "geradors#gerador_arquivo", :via => :get
    match 'result_gerador'   => "geradors#result_gerador", :via => :get
  end
  #login
  resources :logins do
    collection do
      get 'acesso'
      get 'liberacao'
      post 'logar'
      post 'get_unidade'
    end
  end

  #cadastros
  resources :localizacaos
  resources :produto_barras
  resources :localidades
  resources :metodos
  resources :equipos
  resources :servicos
  resources :variavels
  resources :elementos
  resources :unidade_metricas
  resources :empresas
  resources :contas
  resources :sub_grupos
  resources :depositos
  resources :bicos
  resources :grupos
  resources :usuarios
  resources :unidades
  resources :clases
  resources :rodados
  resources :documentos
  resources :metas
  resources :meta_detalhes
  resources :planos
  resources :plano_de_contas do
    collection do
      get 'print'
    end
  end 
  resources :moedas
  resources :cidades
  resources :estados
  resources :paises
  resources :setors
  resources :personas do
    collection do
      get 'persona_nota_credito'
      get 'persona_cobro'
      get 'persona_pago'
      get 'busca_persona_pago'                    
      get 'busca_persona_cobro'                  
      get 'persona_presupuesto'                  
      get 'persona_nota_credito_proveedor'       
      get 'busca_persona_presupuesto'            
      get 'busca'                                
      get 'persona_compra'                 
      get 'busca_persona_compra'                 
      get 'busca_cliente'                        
      get 'busca_persona_nota_credito'           
      get 'busca_persona_nota_credito_proveedor' 
      get 'busca_persona_venda_financa'          
      get 'busca_persona_venda'
      get 'persona_venda'
    end
    member do 
      get 'tarjeta'
    end
  end                   
  resources :produtos do
    collection do
      get 'dinamic_busca_consulta_stock'             
      get 'index_print'                              
      get 'consulta_stock'                           
      get 'busca_compra_produto'                     
      get 'dinamic_busca_compra_produto'             
      get 'busca_composicao_produto'                 
      get 'dinamic_busca_composicao_produto'         
      get 'busca_pedido_compra_produto'              
      get 'dinamic_busca_pedido_compra_produto'      
      get 'busca_presupuesto_produto'                
      get 'dinamic_busca_presupuesto_produto'        
      get 'busca_venda_produto'                      
      get 'dinamic_busca_venda_produto'              
      get 'busca_consumicao_interna_produto'         
      get 'dinamic_busca_consumicao_interna_produto' 
      get 'busca_manutencao_mq_produto'              
      get 'dinamic_busca_manutencao_mq_produto'      
      get 'busca_producao_produto'                   
      get 'dinamic_busca_producao_produto'           
      get 'busca_remicao_produto'                    
      get 'dinamic_busca_remicao_produto'            
      get 'busca_venda_produto_maiorista'            
      get 'dinamic_busca_venda_produto_maiorista'    
      get 'dinamic_busca'                            
      get 'busca_ordem_produto'                      
      get 'dinamic_busca_ordem_produto'              
      get 'imagem'                                  
    end
    member do
      get 'cod_barra'
      get 'roteiro'
      get 'composicao'

    end
  end  
  resources :financas do
    collection do
      get 'relatorio_financas'
      get 'extrato_bancario'
      get 'resultado_extrato_bancario'    

    end  
  end
  resources :forms

  #processos
  resources :controle_pulv_maqs
  resources :controle_pulvs  
  resources :controle_visita
  resources :setores
  #
  resources :controle_pulvs
  resources :controle_visita
  #COMPRAS
  resources :compras_gastos
  resources :compras_documentos
  resources :compras_produtos
  resources :compras_financas
  resources :compras do
    collection do
      get 'busca' 
      get 'busca_gasto'      
      get 'compras_gasto'     
      get 'compras_financa'   
      get 'compras_documento'             
      get 'novo_financa'      
      get 'novo_gasto'        
      get 'new_gasto'
      get 'index_gasto'
      get 'pedido_compras'
    end  
    member do 
      get "compras_financa"
      get "novo_financa" 
      get "edit_gasto"     
      get 'novo_produto'
      get 'compras_documento'
      get 'total_documento'
      get 'novo_documento'
      get 'prorateo'
    end
  end  
  resources :stocks do
    collection do
      get 'iventario'
      get 'stock_inicial'
      get 'relatorio_stock'                  
      get 'rentabilidade'                    
      get 'resultado_rentabilidade'       
      get 'dinamic_busca_stock_inicial'    
      get 'resultado_iventario'              
      get 'resultado_relatorio_consumo_bomba'
      get 'projecao_compras'
      get 'resultado_projecao_compras'      
    end
  end
  resources :pagares do
    member do
      get 'autorizacao_desc'
      get 'print'
    end
  end
   
  
resources :pagares_detalhe

  resources :consumicao_internas do 
    resources :consumicao_interna_produtos  
  end
  resources :ingressos do
    collection do
      get 'busca_ingreso'
    end
    member do
      get 'comprovante'
    end
  end

  resources :presupuestos
  resources :vendas do
    collection do
      get  'new_balcao'
      get  'venda_produto'
      get  'faturas_pendentes'                     
      get  'comprovante'                          
      get  'comprovante_fatura_pendentes'          
      get  'detalhes_produto'                      
      get  'busca_vendas'
      get  'vendas_financa_contado'               
      get  'vendas_financa' 
      get  'gerar_cotas_credito'
      get  'busca_vendas'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante'       
      get  'vendas_entrada_produto'
      post 'filtro_faturas_pendentes'
      post 'filtro_faturas_pendentes_comprovante' 
      put  'update_faturas_pendentes'  
    end
    member do
      get  'vendas_financa'
      get  'gerador_cotas'
      get  'comprovante'
      get  'fatura'
      get  'ticket'
    end 
  end
  resources :vendas_financas

  resources :vendas_produtos
  
  resources :producaos do
    collection do
      get 'busca'
      get 'producao_final'
    end
    resources :producao_produtos do 
      collection do 
        get 'detalhe_print'
      end 
    end 
  end  

  resources :manutencao_maquinas do
    resources :manutencao_maquina_produtos
  end
  resources :recepcao_nota_remicao_produtos
  resources :recepcao_nota_remicaos
  resources :nota_remicao_produtos
  resources :nota_remicaos
  resources :nota_creditos_detalhes
  resources :nota_creditos
  resources :nota_credito_proveedors do
    collection do
      get 'filtro_busca_faturas'
      get 'nc_proveedor_financa'
      get 'nota_credito_comprovante'
    end
  end
  resources :vendas_entrada_produtos
  
  resources :cobros_detalhes
  resources :cobros_financas
  resources :cobros do
    collection do      
      get 'busca'      
      get 'nova_cota'      
      get 'filtro_busca_cliente' 
      get 'busca'
      get 'nova_cota'
    end
    member do 
      get 'filtro_busca_cliente'
      get 'cobro_final'
    end
  end                        
  resources :pagos do
    collection do
      post 'filtro_dividas'
      get  'busca'      
    end
    member do 
      get 'pago_final'
    end
  end
  resources :pagos_detalhes
  resources :pagos_financas
  resources :egressos do
    collection do
      get 'busca_egreso'
      get 'comprovante'
    end
  end
  resources :transferencia_contas_detalhes
  resources :transferencia_contas do
    collection do
      get 'busca_diferido'
      get 'resultado_busca_diferido'
      get 'busca'
    end
  end
  resources :transferencia_entre_contas
  resources :fechamento_caixas
  resources :sueldos_detalhes

  resources :sueldos do
    collection do
      get 'form_sueldos_detalhes'
    end
    member do
      get 'form_sueldos_detalhes'
      get 'comprovante'
    end
  end 
  
  resources :adelantos do
    collection do
      get 'busca'
    end
    member do 
      get 'comprovante'
      get 'recibo'
    end 
  end  
  resources :pedido_compras do
    collection do 
      get 'busca_pedido_compra'
    end
  end
  resources :transferencia_depositos
  resources :entrada_saida_func_detalhes
  resources :entrada_saida_funcs do
    collection do
      get 'busca'
    end
  end

  resources :clientes do
    collection do
      get 'relatorio_contas_receber'
      get 'atualizacao_carpeta_cliente' 
      get 'busca_atualizacao_carpeta_cliente'
      get 'index_inicio'
    end
  end

  resources :proveedores do
    collection do
      get 'relatorio_contas_pagar'
      get 'index_inicio'
    end
  end

  resources :relatorios do
    collection do

app/models/venda.rb
class Venda < ActiveRecord::Base
  has_many :clientes,          :order => 1
  has_many :vendas_produtos,   :order => 1, :dependent => :destroy
  has_many :vendas_financas,   :order => 1, :dependent => :destroy
  has_many :vendas_colaboradors,   :order => 1, :dependent => :destroy  
  has_many :vendas_entrada_produtos,   :order => 1, :dependent => :destroy
  belongs_to :persona

  validates_presence_of :cotacao,
                        :persona_id,
                        :persona_nome

  validates_presence_of :pedido_id, :if => :pedido?
  validates_uniqueness_of :pedido_id, :if => :pedido_dif?

  def pedido?
    self.pedido.to_i == 1
  end

  def pedido_dif?
    self.pedido_id.to_i != 0
  end

  def validate                         
    busca_pedido_cancel = Presupuesto.count(:id,:select => 'id', :conditions => ["status = 2 and id = ?", self.pedido_id])
    if busca_pedido_cancel.to_i > 0
      errors.add_to_base( "Este Pedido esta Cancelado, Por Favor Verifique." ) 
    end

  #VERIFICA SE SALDO E MAIOR QUE A QUANTIDADE DA VENDA
    if ( persona.estado.to_i == 1  )
      errors.add_to_base( "Cliente Bloqueado Consulte a Parte Administrativa" )      
    end
    #divida > que 90 dias
    dividas = Cliente.count(:id, :conditions => ["PERSONA_ID = ? AND LIQUIDACAO = 0 AND ( CURRENT_DATE - (VENCIMENTO+ 90) ) >= 90",self.persona_id])

    if (dividas.to_i >  0  )
      errors.add_to_base( "Cliente Bloqueado Por Pendencias con Mas 90 Dias, Consulte la Parte Administrativa" )      
    end
  end 

  def self.gerador_cotas(params)
    cota = 1
    venc = 0
    valor_gs = params[:valor_gs].to_f / params[:cotas].to_i
    valor_us = params[:valor_us].to_f / params[:cotas].to_i
    params[:cotas].to_i.times do
      VendasFinanca.create( :venda_id        => params[:id],
                            :tipo            => 1,
                            :data            => params[:data],
                            :local_pago      => params[:local_pago],
                            :cotacao         => params[:cotacao],
                            :fatura          => params[:fatura],
                            :vendedor_id     => params[:vendedor_id],
                            :vendedor_nome   => params[:vendedor_nome],
                            :clase_produto   => params[:clase_produto],
                            :fatura_legal    => params[:fatura_legal],
                            :fatura_legal_ruc=> params[:fatura_legal_ruc],
                            :documento_numero_01 => params[:documento_numero_01],
                            :documento_numero_02 => params[:documento_numero_02],
                            :documento_numero    => params[:documento_numero],
                            :persona_id      => params[:persona_id],
                            :persona_nome    => params[:persona_nome],
                            :moeda           => params[:moeda],
                            :cota            => cota,
                            :cota_guarani_01 => valor_gs.to_f,   
                            :cota_dolar_01   => valor_us.to_f,   
                            :data_cota_01    => params[:venci].to_date.months_since(venc.to_i) )
      cota += 1 
      venc += 1                      
      
    end                       

  end 


  def self.filtro_vendas(params)                                         #
    
    cond =  ["data BETWEEN '#{params[:inicio]}' AND '#{params[:final]}' "] unless params[:inicio].blank?
    
    if params[:tipo] == "CODIGO"
      tipo = "id"
      cond =  ["#{tipo} = ? ","#{params[:busca]}"] unless params[:busca].blank?
    elsif params[:tipo] == "DOCUMENTO"
      tipo = "documento_numero "
      cond =  ["#{tipo} LIKE ? ","%#{params[:busca]}%"] unless params[:busca].blank?
    elsif params[:tipo] == "CLIENTE"
      tipo = "persona_nome"
      cond =  ["#{tipo} LIKE ? ","%#{params[:busca]}%"] unless params[:busca].blank?

    end



    Venda.paginate( :select => 'id,data,status,local_venda,vendedor_nome,persona_nome,tipo,documento_numero_01,documento_numero_02,documento_numero,quantidade,total_dolar,total_guarani',
                    :conditions => cond,
                    :page       => params[:page],
                    :per_page   => 25,
                    :order      => 'data desc,id desc')
  end

  def before_save                                                        #
    @vendedor = Persona.find_by_nome(self.vendedor_nome);
    self.vendedor_id = @vendedor.id.to_i unless  self.vendedor_nome.blank?

    @mecanico = Persona.find_by_id(self.mecanico_id);
    self.mecanico_nome = @mecanico.nome.to_i unless  self.mecanico_id.blank?
  end

  def after_save

    if self.pedido.to_i == 1

      VendasProduto.destroy_all("venda_id = #{self.id}" )
      pedido_produto = PresupuestoProduto.all(:conditions => ["presupuesto_id = ?", self.pedido_id])

      pedido_produto.each do |pp|
        VendasProduto.create( :venda_id         => self.id,
                              :data             => self.data,
                              :moeda            => self.moeda,
                              :cotacao          => self.cotacao,
                              :persona_id       => self.persona_id,
                              :persona_nome     => self.persona_nome,
                              :clase_id         => pp.clase_id,
                              :grupo_id         => pp.grupo_id,
                              :deposito_id      => pp.deposito_id,
                              :deposito_nome    => pp.deposito_nome,
                              :taxa             => pp.taxa,
                              :produto_id       => pp.produto_id,
                              :produto_nome     => pp.produto_nome,
                              :fabricante_cod   => pp.fabricante_cod,
                              :quantidade       => pp.quantidade,
                              :unitario_dolar   => pp.unitario_dolar,
                              :unitario_guarani => pp.unitario_guarani,
                              :unitario_real    => pp.unitario_real,
                              :total_dolar      => pp.total_dolar,
                              :total_guarani    => pp.total_guarani,
                              :total_real       => pp.total_real,
                              :total_desconto   => 0,
                              :desconto         => 0,
                              :interes          => 0,
                              :clase_produto    => 0,
                              :vendedor_id      => self.vendedor_id,
                              :vendedor_nome    => self.vendedor_nome,
                              :preco_dolar      => pp.unitario_dolar,
                              :preco_guarani    => pp.unitario_guarani,
                              :preco_fixo_dolar => pp.unitario_dolar, 
                              :preco_fixo_guarani => pp.unitario_guarani, 
                              :preco_fixo_real => pp.unitario_real )
      end
      Presupuesto.find(self.pedido_id).update_attributes(:status => 1,:venda_id => self.id)
    end
    
  end


end

app/views/vendas/eps/_index_financa_E03.html.erb
<div class="group">
   <table>
      <tr>
         <td width="50" align="center">Cota</td>
         <td width="50" align="center">Tipo</td>
         <td width="50" align="center">Moneda</td>         
         <td width="100" align="center">Cheque</td>
         <td width="100" align="center">Valor Dolar</td>
         <td width="100" align="center">Valor Gs.</td>
         <% if @venda.tipo == 0 %>
            <td width="200" align="center">Cuenta</td>
            <td width="100" align="center">Dif.</td>
            <td width="150" align="center">Banco</td>
            <td width="150" align="center">Titular</td>
         <% else %>
            <td width="100" align="center">Venci.</td>

         <% end %>

      </tr>
   </table>

   <div class="rolagem_cobro" dir="div">
      <table>
            <%  vendas_financas.each do |vendas_financa| %>

               <tr class = "<%= cycle("cor2", "cor1") %>">
                  <td width="50" align="center">    <%= h vendas_financa.cota %></td>
                  <% if vendas_financa.tipo.to_i == 0 %>
                     <td width="50" align="center">CONTADO</td>
                  <% else %>
                     <td width="50" align="center">CREDITO</td>
                  <% end %>
                  <% if vendas_financa.moeda.to_i == 0 %>
                     <td width="50" align="center">U$</td>
                  <% elsif vendas_financa.moeda.to_i == 1 %>
                     <td width="50" align="center">Gs</td>
                  <% else %>
                     <td width="50" align="center">R$</td>
                  <% end %>
                  
                  <% if vendas_financa.tipo == 0  %>
                     <td width="100" align="left">    <%= h vendas_financa.cheque %></td>
                     <td width="100" align="right">   <%= h number_to_currency(vendas_financa.valor_dolar_contado, :format=>' %n ', :separator => ",")  %></td>
                     <td width="100" align="right">   <%= h number_to_currency(vendas_financa.valor_guarani_contado, :format=>' %n ', :precision => 0)  %></td>
                     <td width="200" align="left">    <%= h vendas_financa.conta_nome %></td>
                     <td width="100" align="center">  <%= h vendas_financa.diferido.strftime("%d/%m/%Y") %></td>
                     <td width="150" align="left">  <%= h vendas_financa.banco %></td>
                     <td width="150" align="left">  <%= h vendas_financa.titular %></td>
                  <% else %>
                     <td width="100" align="left">    <%= h vendas_financa.cheque %></td>
                     <td width="100" align="right">   <%= h number_to_currency(vendas_financa.cota_dolar_01, :format=>' %n ', :separator => ",")  %></td>
                     <td width="100" align="right">   <%= h number_to_currency(vendas_financa.cota_guarani_01, :format=>' %n ', :precision => 0)  %></td>
                     <td width="100" align="center">  <%= h vendas_financa.data_cota_01.strftime("%d/%m/%Y") %></td>
                  <% end %>
                  <td><%= link_to 'Editar', edit_vendas_financa_path(vendas_financa) %></td>
                  <td><%= link_to 'Borrar', vendas_financa, :confirm => 'Tiene Certeza?', :method => :delete %></td>
               </tr>
            <% end %>
      </table>
   </div>
</div>

app/views/vendas/eps/_new_produto_E06.html.erb
<!-- form base balcao! -->
<div class="group">
  <%= form_for(vendas_produto) do |f| %>
    <%= f.hidden_field :venda_id %>
    <div class="right">    	
    	<%= f.text_field :barra, :class => 'medium', :placeholder => 'barra' %>
    	<br>

    	<div class="valores">
          <div class="texts">
            <span>Cantidad:</span>
            <%= f.text_field :quantidade, :class => 'small' %>            
          </div>
        	<br>
          <div class="texts">
            <span>Unit.:</span>
            <%= f.text_field :unitario_guarani, :class => 'small' %>
            </div>
          <br>
          <div class="texts">
          	<span>Sub-Total:</span>
            <%= f.text_field :unitario_guarani, :class => 'small' %>
          </div>

    	</div>
    <%= f.text_field :produto_nome, :class => 'large', :placeholder => 'Producto' %>

    </div>
    
wewewe
    <div class="right">    	
    		<table width="510">
    			<tr>
    				<td></td>
    			</tr>
    		</table>
    </div>

  <% end %>
</div>

app/views/vendas/eps/_show_E01.html.erb
<ul class="tabs">
  <li><a href="#tab1">Venta [Producto]</a></li>
</ul>
<div class="tab_container">
	<table>
       <tr>
           <td>
    <div class="group">
	  <table>
		<tr>
			<td align="right">Cliente : </td>
			<td><%= @venda.persona_nome %></td>

			<td align="right">Ruc : </td>
			<td><%= @venda.ruc %></td>

			<td align="right">Clasificacion : </td>
			<td><%= @venda.classificacao   %></td>

			<td align="right">Cliente : </td>
			<% if @venda.tipo_maiorista == 0  %>
			<td>Balcao</td>
			<% elsif @venda.tipo_maiorista == 1%>
			<td>Mayorista</td>
			<% elsif @venda.tipo_maiorista == 2%>
			<td>Corporativo</td>
			<% else %>
			<td>Balcao</td>
			<% end %>
		</tr>

		<tr>
			<td align="right">Limite Credito :</td>
			<td align="right"><%= number_to_currency( @venda.limite_credito, :format=>' %n ', :separator => ",",:precision => 0) %></td>

			<td align="right">Saldo Disponivel :</td>
			<td align="right"><%= number_to_currency( @venda.limite_credito, :format=>' %n ', :separator => ",",:precision => 0) %></td>

			<td align="right">Cotizacion:</td>
			<td align="right"><%= number_to_currency( @venda.cotacao, :format=>' %n ', :separator => ",",:precision => 0) %></td>

		</tr>
	</table>
  </div>           
   </td>

   <td rowspan="3" valign="top">
   	<br/>
   	Legend<br/>
   	( F4 ) - Seguir <br/>
   	( Ctrl + 1 )  - descuento <br/>
   	( F2 ) - Busca por Descrip. <br/>
   	( Ctrl + C ) Busca por Cod. <br/>
   	( Ctrl + B ) Busca por Barra <br/>


   </td>
       </tr>

		<tr>
			<td>
			<div class="group">
				<table class="head_grid">
					<tr>
						<td width="50" align="center">Cod.</td>
						<td width="350" align="center">Producto</td>
						<td width="80" align="center">Cantidad</td>
						<td width="80" align="center">Unit </td>
						<td width="80" align="center">Total </td>
						<td width="80" align="center">Iva.</td>
						<td width="80" align="center">Descuento</td>
						<td width="90"></td>

					</tr>
				</table>
				<div class="rolagem" dir="div">
					<div id="vendas_produtos">
						<%= render :partial => @venda.vendas_produtos %>
					</div>
				</div>
			</div>

			</td>
		</tr>

		<tr>
			<td align="center">
			<div class="group">
				<table>
					<tr>
						<% if @venda.moeda == 0 %>

							<td>
								<font class="style3" color="green">Total U$.:</font>
								<font class="style3" color="green">
									<span id="total_dolar">	<%= number_to_currency(@total_dolar, :format=>' %n ', :separator => ",") %></span>
								</font>
							</td>

						<% elsif @venda.moeda == 1 %>

							<td>
								<font class="style3" color="red">Total Gs.:</font>
								<font class="style3" color="red">
									<span id="sub_total"><%= number_to_currency(@total_guarani, :format=>' %n ',:precision => 0) %></span>
								</font>													
							</td>

						<% else %>

							<td>
								<font class="style3" color="blue">Total R$.:</font>
								<font class="style3" color="blue">
									<span id="total_real"><%= number_to_currency(@total_real, :format=>' %n ', :separator => ",") %></span>
								</font>													
							</td>
						<% end %>

					</tr>
				</table>
			</div>
			</td>
		</tr>

		<tr>
			<td><%= render :partial => "/vendas_produtos/new_produto" %></td>
		</tr>
	</table>


	<div class="buttons">
		<%= link_to 'Volver (F3)', vendas_path, :class => "button back" %>

		   <%= link_to 'Seguir (F4)', vendas_financa_vendas_path(:id => @venda.id) , :class => "button next" %>
		   <%= hidden_field_tag :id, @venda.id %>
		   <%= hidden_field_tag :moeda, @venda.moeda %>
		   <%= hidden_field_tag :maiorista, @venda.tipo_maiorista %>
		</div>
	</div>


<script>

	document.onkeydown= function(e) {
		var cliente  = document.getElementById('maiorista').value
		var deposito = document.getElementById('vendas_produto_deposito_id').value
		//BOTAO F4
		if(e.which == 115)
			location.href="/vendas/"+ document.getElementById('id').value + "/vendas_financa"
		//back 
		if(e.which == 114)
			location.href="/vendas/"

		//LISTA DE PRODUTOS
		if(e.which == 113)
			window.open('/produtos/busca_venda_produto?cliente='+cliente+'&deposito_id='+deposito+'', 'Pagina', ' SCROLLBARS=YES, TOP=10, LEFT=50, WIDTH=2500, HEIGHT=400');

	}
</script>

app/views/vendas/eps/_show_E02.html.erb
<div class="group">
	<div class="left">    	
			<table class="head_grid">
				<tr>
					<td width="50" align="center">ind.</td>
					<td width="680"align="left">Descripcion</td>
					<td width="70" align="right">Qtd</td>
					<td width="70" align="right">Unit</td>
					<td width="70" align="right">Tot.</td>
					<td width="110"></td>
					

				</tr>
			</table>
			<div class="rolagem" dir="div">
				<div id="vendas_produtos">					
				  	<%= render :partial => @venda.vendas_produtos %>
				</div>
			</div>

	</div>
	<%= render :partial=>Form.last.form_venda_produtos %>	  

	<div class="backgrounds">
	<div class="buttons">
		<%= link_to 'Volver (F3)', vendas_path, :class => "button back" %>

		   <%= link_to 'Seguir (F4)', vendas_financa_vendas_path(:id => @venda.id) , :class => "button next" %>
		   <%= hidden_field_tag :id, @venda.id %>
		   <%= hidden_field_tag :moeda, @venda.moeda %>
		   <%= hidden_field_tag :maiorista, @venda.tipo_maiorista %>
		</div>
	</div>

</div>


<script>
	function ComprovanteOrden()                //
	{
		window.open('/vendas/requerimento_ordem_servico/' + document.getElementById('id').value, 'Pagina', ' SCROLLBARS=YES, TOP=250, LEFT=500, WIDTH=600, HEIGHT=400');
	}

	document.onkeydown= function(e) {
		var cliente  = document.getElementById('maiorista').value
		var deposito = document.getElementById('vendas_produto_deposito_id').value
		//BOTAO F4
		if(e.which == 115)
			location.href="/vendas/"+ document.getElementById('id').value + "/vendas_financa"
		//back 
		if(e.which == 114)
			location.href="/vendas/"

		//LISTA DE PRODUTOS
		if(e.which == 113)
			window.open('/produtos/busca_venda_produto?cliente='+cliente+'&deposito_id='+deposito+'', 'Pagina', ' SCROLLBARS=YES, TOP=10, LEFT=50, WIDTH=2500, HEIGHT=400');

	}
</script>